---
title: "Project 3"
author: "Transcriptomics Noob"
date: "3/3/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Collaboration with Git

For this project, all members of the class will be working on the same git repo. 
This could pose all kinds of problems for pushing changes, if we don't follow the proper process of forking the repo. 
This tutorial is adapted from <http://r-bio.github.io/intro-git-rstudio/>.

### Branching

We will each create a branch of the RNASeqProject repo on the <https://github.com/Bucknell-Biol364/RNASeqProject> page.
On the top right, click `Fork`. 
Then click your personal Github account, to create the branch there.

Github should redirect you to the new forked repo, which is an exact copy of the original repo.
Now use R Studio, New Project, Version Control, Git... to make a local repo of **your** branch. 

After it has been cloned, we need to tell Git that this project has an upstream version. 
There is no way of doing this within RStudio, so you need to enter some commands in the shell. 
Go to Tools > Shell, and enter the address of the upstream repository

`git remote add upstream https://github.com/Bucknell-Biol364/RNASeqProject.git`

<<<<<<< HEAD
Make sure that it worked by typing `git remote -v` in the shell.
It should display 4 lines, 2 that start with `origin` and the address of your fork, and 2 that start with `upstream` and the address of the upstream repository. 
Note that here we used `upstream` to name the upstream repository but we could have given it another name. 
In this case, upstream is just easy to remember and accurate. 

Now switch back to R Studio and create a new **branch** to store your changes so they are separate from your master repo.
Click `New Branch` in the Git tab.
Name it test-branch or something relevant for the changes you plan.

=======
>>>>>>> 42ef1e1c641f66ccd98824bff2d099c938e06d9e
Edit the Test.txt file by adding a line or two and save it.
You should now be able to Commit and Push this change to Github. 
However, you have **NOT** changed the class repo, only your own account's copy of it. 
You can use this personal copy to perform your analysis and to Commit and Push changes as often as you like. 
The stakes are higher now, because eventually you will be merging your personal copy with the class master copy. 
Two new best practices should be followed:

1. Use meaningful Committ messages. This will help others to know whether to pull your changes.
2. Do not change the original files. Make a copy of a file before changing it and then name it using your name.

The exception to this second rule will be Test.txt because we want to create some git conflicts.
After pushing the changes to Test.txt to your personal repo, go back to github.com and refresh the page showing this repo. 
