---
title: "Group Project: Tables"
author: "The table group"
date: "3/26/2019"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
---

# Loading in Tables
```{r}
bowtie_deseq_table <- read.csv("tables/bowtie2_deseq2_transcript.csv") 
bowtie_edgeR_table <- read.csv("tables/Bowtie2EdgeR_McGauley.csv")
bowtie_limma_table <- read.csv("tables/Moore_bowtie_limma.csv")

kallisto_edgeR_table <- read.csv("tables/julie_kallisto_edgeR_final.csv")
kallisto_limma_table <- read.csv("tables/SimpsonTable.csv")
kallisto_deseq_table <- read.csv("tables/kallistoDESeq_Sussman.csv")
kallisto_deseq_table <- kallisto_deseq_table[1:4]


salmon_limma_table <- read.csv("tables/McKinleySalmonLimmaGeneInfo.csv")
salmon_edgeR_table <- read.csv("tables/KE_Salmon_EdgeR_final.csv")
salmon_deseq_table <- read.csv("tables/salmondeseq2.csv")

sailfish_limma_table <- read.csv("tables/Ritter_sailfish_limma.table.csv")
sailfish_edgeR_table <- read.csv("tables/JustinKoss.sailfish.edgeR.updown.csv")
sailfish_deseq_table <- read.csv("tables/Vogel_Sailfish_DESeq2.csv")

```

#Creating a super table
```{r}
complete_table <- rbind(bowtie_deseq_table, bowtie_edgeR_table, bowtie_limma_table, kallisto_edgeR_table, kallisto_limma_table, kallisto_deseq_table, salmon_limma_table, salmon_edgeR_table, salmon_deseq_table, sailfish_limma_table, sailfish_edgeR_table, sailfish_deseq_table)
write.csv(complete_table, file ="tables/All_pipelines_complete_table.csv", quote = FALSE)

```

```{r}
if (!require("VennDiagram")) install.packages("Venndiagram"); library(VennDiagram)

#url to package info: https://cran.r-project.org/web/packages/VennDiagram/VennDiagram.pdf

#url to tutorial: https://rstudio-pubs-static.s3.amazonaws.com/13301_6641d73cfac741a59c0a851feb99e98b.html

#looks like we can use "draw.triple.venn()" and "draw.quad.venn()". Check out the tutorial for some good info about specifics but it looks like we just need the sizes of each group (genes by bowtie, kallisto, etc). There are also some functions that appear to generate lists of different portions shared by the groups
```

